### ISSUE TITLE
What's the difference between multi-class and multi-label?

### ISSUE THREAD

**Issue by SilenceWinter** [xueyouluo/attention-text-classification#1]
if self.hparams.label_type == 'multi-class':
                self.label_predict = self.label_outputs
elif self.hparams.label_type == 'multi-label':
                self.label_predict = tf.sigmoid(self.label_outputs)

**Comment by xueyouluo** [comment]
Refer to the [doc](https://scikit-learn.org/stable/modules/multiclass.html).

Multiclass classification means a classification task with more than two classes; e.g., classify a set of images of fruits which may be oranges, apples, or pears. Multiclass classification makes the assumption that each sample is assigned to one and only one label: a fruit can be either an apple or a pear but not both at the same time.

Multilabel classification assigns to each sample a set of target labels. This can be thought as predicting properties of a data-point that are not mutually exclusive, such as topics that are relevant for a document. A text might be about any of religion, politics, finance or education at the same time or none of these.
